### ISSUE TITLE
Train process aborting during Batch Run "0"

### ISSUE THREAD

**Issue by ghost** [mitaki28/rnn-morpheme-analyzer#1]
![bi-rnn error](https://cloud.githubusercontent.com/assets/6353559/13754823/b594bade-ea18-11e5-9c5d-cfd34864584b.png)

I am using python3 to run your code on a small sample of text.

Batch 0 shows running and then after about 30 seconds it abords.

No error message nothing.

Can you please advise?

Thanks

**Comment by mitaki28** [comment]
I have fixed this issue.
Now, model is saved when all sentences are processed.

**Comment by ghost** [comment]
Thank you very much.
