### ISSUE TITLE
Train process aborting during Batch Run - even with latest version

### ISSUE THREAD

**Issue by ghost** [mitaki28/rnn-morpheme-analyzer#2]
Hi,

I am using CPU to test your latest code.

Please see picture, the process killed itself on checkpoint 0 with Batch finalized by only 2 percent.

Thank you.
![rnn error](https://cloud.githubusercontent.com/assets/6353559/13924175/9fd6e22e-ef83-11e5-9b45-d26f2025d519.png)

**Comment by mitaki28** [comment]
Sorry for confusing interface. It's not aborted.
Your model is correctly saved in cv/model-_K_.model and cv/optimizer-_K_.model. (_K_ is a certain number. )
You can use model if you execute `python segmentation.py run cv K`

Progress bar shows the number of processed sentences in the current checkpoint, which is group of 1000 sentences.
If reminder of sentences is smaller than 1000, program will terminate before reaching 100%.
